name: Docker Image CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile_GithubActions --tag test-env:latest
      - name: Check Docker Image
        run: docker images
      - name: Start Docker Container
        run: docker run -d --name my-container -v $PWD/tinyxml2:/work test-env:latest
      - name: Check Docker Container Logs
        run: docker logs my-container
      - name: Run Test Config Inside Docker
        run: docker exec my-container bazel test --config=clang12_config --config=asan //:xmltest
      - name: Show Test Output
        run: docker exec my-container cat /work/bazel-testlogs/xmltest_memleak/test.log
      - name: Copy Test Logs from Docker Container
        run: docker cp my-container:/work/bazel-testlogs/xmltest_memleak/test.log $GITHUB_WORKSPACE/test.xml
      - name: Show Test Output
        run: cat test.log
      - name: Upload Logs as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-logs
          path: /work/bazel-testlogs/xmltest_memleak/test.xml
      - name: Stop and Remove Docker Container
        run: docker stop my-container && docker rm my-container
      - name: Check Bazel Test Exit Code
        run: exit ${{ job.status }}
        if: ${{ job.status != 'success' }}