name: Docker Image CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #config: [ "--config=clang12_config --config=asan", "--config=clang12_config --config=tsan", "--config=asan", "--config=tsan", "" ]
        config: [ "" ]
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker Image
        run: docker build . --file Dockerfile_GithubActions --tag test-env:$(date +%s)
      - name: Start Docker Container
        run: docker run -d --name my-container test-env:$(date +%s)
      - name: Run Test Config Inside Docker Container
        id: runTest
        run: docker exec my-container bazel test ${{ matrix.config }} //:xmltest
        continue-on-error: true
      - name: Show Test Output
        run: docker exec my-container cat /work/bazel-testlogs/xmltest/test.xml
      - name: Copy Test Logs from Docker Container
        run: docker cp my-container:/work/bazel-testlogs/xmltest/test.xml $GITHUB_WORKSPACE/test.xml
      - name: Show Test Output
        run: cat test.xml
      - name: Upload Logs as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-logs
          path: test.xml
      - name: Stop and Remove Docker Container
        run: docker stop my-container && docker rm my-container
      - name: Check Bazel Test For Errors
        if: steps.runTest != 'success'
        run: exit 1


      # - name: Show Test Output
      #   run: docker exec my-container cat /work/bazel-testlogs/xmltest_memleak/test.xml
      # - name: Copy Test Logs from Docker Container
      #   run: docker cp my-container:/work/bazel-testlogs/xmltest_memleak/test.xml $GITHUB_WORKSPACE/test.xml
      # - name: Show Test Output
      #   run: cat test.xml
      # - name: Upload Logs as Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: build-logs
      #     path: /work/bazel-testlogs/xmltest_memleak/test.xml
      # - name: Stop and Remove Docker Container
      #   run: docker stop my-container && docker rm my-container
      # - name: Check Bazel Test For Errors
      #   if: steps.runTest != 'success'
      #   run: exit 1