name: Docker Image CI
on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Start Docker Container
      run: docker run -it --rm -v $PWD/tinyxml2:/work my-image-name:$(date +%s)
    - name: Run Test Config Inside Docker
      run: bazel test --config=clang12_config --config=asan //:xmltest
    - name: Show Test Output
      run: ccat /work/bazel-testlogs/xmltest_memleak/test.log
    
